[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "my_app_db"
version = "0.1.0"
description = "Shared Database Models and Connection relying on MongoEngine"
dependencies = [
    "mongoengine>=0.27.0"
]

[tool.setuptools.packages.find]
where = ["src"]
