[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "my_app_config"
version = "0.1.0"
description = "Shared Configuration"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]
